### ISSUE TITLE
tasks and works center

### ISSUE THREAD

**Issue by saran-gangster** [saran-gangster/Sector-17#1]
### For Murari and Aravind create a gui
_**work**_
1.display these [gui](https://media.tenor.com/images/9f24fecd73b30cc93ff65efb438f2735/tenor.gif) _5 times_
2.then display these [gui](https://images.squarespace-cdn.com/content/v1/51be3e56e4b09edc5f81e74c/1551795622591-1FBFE410OXSXACYA5C8Q/ke17ZwdGBToddI8pDm48kFTEgwhRQcX9r3XtU0e50sUUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKc2PPwcWkLXq-DNe4zpT7he0M_zRUr6912vvtObYWjAW-pUdJURR5nHbHpk7AZw8X9/SciFi_WaspYellow.gif?format=1500w) _1 time_
3.finally [these](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/d826d7c8-ed2e-4c5b-a53a-639f8ed71b07/da2h0ba-4f905a80-3438-48c6-957f-3ef873f7e7f4.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvZDgyNmQ3YzgtZWQyZS00YzViLWE1M2EtNjM5ZjhlZDcxYjA3XC9kYTJoMGJhLTRmOTA1YTgwLTM0MzgtNDhjNi05NTdmLTNlZjg3M2Y3ZTdmNC5naWYifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.QvW2snLgocmN2K3f90xL_NWnnGRUao8-Psg152oRJao) _infinite_
_**Acknowledgements**_
[java_gui](https://stackoverflow.com/questions/2935232/show-animated-gif)
[Displaying the gui](https://codeloop.org/python-pyglet-adding-gif-image/) ,

**Comment by me-coder-1204** [comment]
I will do. No worries

**Comment by saran-gangster** [comment]
I did the whole gui work so no need thanks
